apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - test.demontwin.my.id
      secretName: static-site-tls
  rules:
    - host: test.demontwin.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static-site-svc
                port:
                  number: 80
