apiVersion: v1
kind: Service
metadata:
  name: static-site-svc
  namespace: default
spec:
  selector:
    app: static-site
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
